name: geospatial
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - shapely
  - spyder
  - pyqtwebengine
  - pandas
  - geopandas
  - rasterio
  - fiona
  - descartes
  - ipython
  - jupyter
  - matplotlib
  - sqlalchemy
  - psycopg2
  - boto3
  - smart_open
  - scikit-learn-intelex
  - progressbar2
  - tqdm
  - gdal
  - libgdal-pg
  # - conda-forge::pysolar
prefix: /home/user/miniconda3/envs/geospatial
